### ISSUE TITLE
"open titles.json: no such file or directory" when said file is in the directory

### ISSUE THREAD

**Issue by LawfulPoe** [Xpl0itU/MLCRestorerDownloader#3]
Using macOS Sonoma 14.0 on a M2 Pro, the "open titles.json: no such file or directory" error keeps happening after selecting an option even when said file exists. I would post the history file logs but I do not know where they are stored. Tested using both the x86_64 and the arm64 builds.

**Comment by LawfulPoe** [comment]
I attempted to use the Windows version of this program and it was successful.

**Comment by Xpl0itU** [comment]
You can’t simply double click on the executable, you have to open a terminal, cd to the directory in which both files are and execute the program with ./MLCRestorerDownloader

**Comment by xorinzor** [comment]
This should be added to a readme, as the release does not include the JSON file. I had to download this separately from the repo.
Additionally, if you just double click the exe you will never see this error (which most users probably do).

Thankfully, once downloaded everything works correctly.
